---
- hosts: localhost
  connection: local
  vars_files:
    - ./vars/symlinks.yml
    - ./vars/apps.yml
    - ./vars/dev.yml

  tasks:
    - name: "Install apps"
      become: true
      become_method: su
      pacman:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ apps }}"

    - name: "Install dev apps"
      become: true
      become_method: su
      pacman:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ dev }}"


    - name: "locaweb: Install fortclient"
      become: true
      become_method: su
      pacman: name=forticlientsslvpn state=present


    - name: Set zsh for {{ user }}
      user: name={{ user }} shell=/bin/zsh

    - include: tasks/dot-files.yml
