---
- hosts: localhost
  connection: local
  vars_files:
    - ./vars/rvm.yml

  roles:
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }

  tasks:
    - include: tasks/gnome_shell_extensions.yml

    - include: tasks/install_apps.yml

    - include: tasks/install_aur_apps.yml

    - name: "Set zsh for {{ ansible_user_id }}"
      become: true
      become_method: su
      user: name={{ ansible_user_id }} shell=/bin/zsh

    - include: tasks/dot_files.yml

    - name: "Clone Tmux plugin manager"
      git:
        repo: git@github.com:tmux-plugins/tpm.git
        dest: ~{{ ansible_user_id }}/.tmux/plugins/tpm

    - name: "Copy ssh config"
      template:
        src: files/config
        dest: ~{{ ansible_user_id }}/.ssh/config

    - name: "Install vundle plugins"
      shell: vim +PluginInstall +qall

    - name: "Install tmux plugins"
      shell: ~{{ ansible_user_id }}/.tmux/plugins/tpm/scripts/install_plugins.sh
