---
- hosts: localhost
  connection: local
  vars_files:
    - ./vars/apps.yml
    - ./vars/dev.yml
    - ./vars/gnome_shell_extensions.yml
    - ./vars/symlinks.yml
    - ./vars/work.yml

  tasks:
    - name: "Install gnome shell extensions"
      shell_extension:
        uri: "{{ item.uri }}"
        name: "{{ item.name }}"
        state: enabled
      with_items: "{{ gnome_shell_extensions }}"

    - name: "Install apps"
      become: true
      become_method: su
      pacman:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ apps }}"

    - name: "Install dev apps"
      become: true
      become_method: su
      pacman:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ dev }}"


    - name: "Install work apps"
      become: true
      become_method: su
      pacman:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ work }}"

    - name: Set zsh for {{ ansible_user_id }}
      user: name={{ ansible_user_id }} shell=/bin/zsh

    - include: tasks/dot-files.yml
