---
- hosts: localhost
  connection: local

  tasks:
    - include: tasks/gnome_shell_extensions.yml

    - include: tasks/install_apps.yml

    - include: tasks/install_aur_apps.yml

    - name: "Set zsh for {{ ansible_user_id }}"
      user: name={{ ansible_user_id }} shell=/bin/zsh

    - include: tasks/dot_files.yml

    - name: "Copy ssh config"
      template:
        src: files/config
        dest: ~{{ ansible_user_id }}/.ssh/config
