---
- name: "dot-files: Clone project for {{ user }}"
  git:
    repo: git@github.com:nvieirafelipe/dot-files.git
    dest: ~{{ user }}/Developer/dot-files
    accept_hostkey: yes

- name: "dot-files: Create symlinks"
  become: true
  become_method: su
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ symlinks }}"
