---
- name: Clone dot-files for {{ user }}
  git:
    repo: git@github.com:nvieirafelipe/dot-files.git
    dest: ~{{ user }}/Developer/dot-files
    accept_hostkey: yes
    update: yes

- name: Create symlinks
  become: yes
  become_method: su
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ symlinks }}"
