---
- include_vars: gnome_shell_extensions.yml

- name: "Install gnome shell extensions"
  shell_extension:
    uri: "{{ item.uri }}"
    name: "{{ item.name }}"
    state: enabled
  with_items: "{{ gnome_shell_extensions }}"
