dev:
  - name: bower
  - name: byzanz-git
  - name: direnv
  - name: elixir
  - name: git
  - name: gnome-terminal-transparency
  - name: heroku-toolbelt
  - name: imagemagick
  - name: nodejs
  - name: npm
  - name: oh-my-zsh-git
  - name: redis
  - name: tmate
  - name: vim
  - name: vundle-git
  - name: zsh
