---

- name: "Download {{ package }}"
  get_url:
    url: https://aur.archlinux.org/cgit/aur.git/snapshot/{{ package }}.tar.gz
    dest: /tmp

- name: "Unpack {{ package }}"
  unarchive:
    src: /tmp/{{ package }}.tar.gz
    dest: /tmp/
    copy: no

- name: "Build {{ package }}"
  shell: cd /tmp/{{ package }} && makepkg -s -i --noconfirm
